load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "HelloShow",
    srcs = ["HelloShow.cpp"],
    hdrs = ["HelloShow.h"],
    copts = ["-IHelloShow"],
    visibility = ["//visibility:public"],
)