load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "TimeShow",
    srcs = ["TimeShow.cpp"],
    hdrs = ["TimeShow.h"],
    copts = ["-ITimeShow"],
    visibility = ["//visibility:public"],
)