

cc_test(
    name = "HelloShowUt",
    # size = "small",
    srcs = ["HelloShowUt.cc"],
    copts = ["-IHelloShow"],
    deps = ["@com_google_googletest//:gtest_main",
            "//HelloShow:HelloShow"],
)