
name: CI

on: 
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel test --test_output=all HelloShow/UnitTests:HelloShowUt
      - run: bazel run TheShower:TheShower
